# Generated by Django 6.0.6 on 2026-06-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Fruits', 'Fruits'), ('Dairy', 'Dairy'), ('Beverages', 'Beverages'), ('Grains', 'Grains'), ('Vegetables', 'Vegetables')], max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
    ]
